<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoCatalogSeeder extends Seeder
{
    public function run(): void
    {

        DB::table('groups')->insert([
            ['id'=>1,'id_parent'=>0,'name'=>'Электроника'],
            ['id'=>2,'id_parent'=>0,'name'=>'Одежда'],
            ['id'=>3,'id_parent'=>0,'name'=>'Бытовая техника'],
            ['id'=>4,'id_parent'=>1,'name'=>'Телефоны и смарт-часы'],
            ['id'=>5,'id_parent'=>1,'name'=>'Компьютеры и комплектующие'],
            ['id'=>6,'id_parent'=>2,'name'=>'Женщинам'],
            ['id'=>7,'id_parent'=>2,'name'=>'Мужчинам'],
            ['id'=>9,'id_parent'=>3,'name'=>'Крупная бытовая техника'],
            ['id'=>10,'id_parent'=>3,'name'=>'Встраиваемая бытовая техника'],
            ['id'=>11,'id_parent'=>4,'name'=>'Смартфоны'],
            ['id'=>12,'id_parent'=>4,'name'=>'Смарт-часы и фитнес-браслеты'],
            ['id'=>13,'id_parent'=>5,'name'=>'Комплектующие для ПК'],
            ['id'=>14,'id_parent'=>5,'name'=>'Моноблоки'],
            ['id'=>15,'id_parent'=>5,'name'=>'Системные блоки'],
            ['id'=>16,'id_parent'=>6,'name'=>'Блузы и рубашки'],
            ['id'=>17,'id_parent'=>7,'name'=>'Брюки'],
            ['id'=>18,'id_parent'=>7,'name'=>'Верхняя одежда'],
            ['id'=>19,'id_parent'=>9,'name'=>'Холодильники'],
            ['id'=>20,'id_parent'=>9,'name'=>'Морозильные камеры'],
            ['id'=>21,'id_parent'=>10,'name'=>'Стиральные машины'],
            ['id'=>22,'id_parent'=>10,'name'=>'Сушильные машины'],
            ['id'=>23,'id_parent'=>10,'name'=>'Посудомойки'],
            ['id'=>24,'id_parent'=>12,'name'=>'Смарт-часы'],
            ['id'=>25,'id_parent'=>12,'name'=>'Фитнес-браслеты'],
            ['id'=>26,'id_parent'=>12,'name'=>'Браслеты и кольца бесконтактной оплаты'],
            ['id'=>27,'id_parent'=>13,'name'=>'Жесткие диски, SSD и сетевые накопители'],
            ['id'=>28,'id_parent'=>13,'name'=>'Видеокарты и графические ускорители'],
            ['id'=>29,'id_parent'=>13,'name'=>'Оперативная память'],
            ['id'=>30,'id_parent'=>13,'name'=>'Материнские платы'],
            ['id'=>31,'id_parent'=>13,'name'=>'Процессоры'],
            ['id'=>32,'id_parent'=>16,'name'=>'Блузы'],
            ['id'=>33,'id_parent'=>16,'name'=>'Рубашки']
        ]);

        DB::table('products')->insert([
            ['id'=>1,'id_group'=>11,'name'=>'Смартфон Apple iPhone 12 mini 128 ГБ'], 
            ['id'=>2,'id_group'=>11,'name'=>'Смартфон Xiaomi Redmi 9A 2/32 ГБ, серый'], 
            ['id'=>3,'id_group'=>11,'name'=>'Смартфон Xiaomi Redmi Note 11 4/128 ГБ, голубой'], 
            ['id'=>4,'id_group'=>11,'name'=>'Смартфон Xiaomi 12 Pro 12/256 ГБ, фиолетовый'], 
            ['id'=>5,'id_group'=>24,'name'=>'Умные часы Pro Smart Watch 7'], 
            ['id'=>6,'id_group'=>24,'name'=>'Умные часы Smart Watch 7 Series'], 
            ['id'=>7,'id_group'=>25,'name'=>'Фитнес-браслет Xiaomi Mi Band 7'], 
            ['id'=>8,'id_group'=>26,'name'=>'Ремешок для часов Huawei Watch Fit'], 
            ['id'=>9,'id_group'=>26,'name'=>'Умное кольцо UK2 NFC'], 
            ['id'=>10,'id_group'=>26,'name'=>'Смарт-кольцо R5 NFC'],
            ['id'=>11,'id_group'=>27,'name'=>'SSD Samsung 970 EVO Plus 1TB'],
            ['id'=>12,'id_group'=>27,'name'=>'SSD Kingston NV2 500GB'],
            ['id'=>13,'id_group'=>27,'name'=>'Жесткий диск WD Blue 1TB'],
            ['id'=>14,'id_group'=>27,'name'=>'SSD Crucial MX500 1TB'],
            ['id'=>15,'id_group'=>27,'name'=>'SSD Samsung 980 PRO 2TB'],
            ['id'=>16,'id_group'=>28,'name'=>'Видеокарта NVIDIA RTX 3060'],
            ['id'=>17,'id_group'=>28,'name'=>'Видеокарта NVIDIA RTX 3070'],
            ['id'=>18,'id_group'=>28,'name'=>'Видеокарта NVIDIA RTX 3080'],
            ['id'=>19,'id_group'=>28,'name'=>'Видеокарта AMD Radeon RX 6600'],
            ['id'=>20,'id_group'=>28,'name'=>'Видеокарта AMD Radeon RX 6700 XT'],
            ['id'=>21,'id_group'=>29,'name'=>'Оперативная память Kingston Fury 16GB'],
            ['id'=>22,'id_group'=>29,'name'=>'Оперативная память Corsair Vengeance 16GB'],
            ['id'=>23,'id_group'=>29,'name'=>'Оперативная память G.Skill Ripjaws 32GB'],
            ['id'=>24,'id_group'=>29,'name'=>'Оперативная память Crucial 8GB'],
            ['id'=>25,'id_group'=>29,'name'=>'Оперативная память Patriot Viper 16GB'],
            ['id'=>26,'id_group'=>30,'name'=>'Материнская плата ASUS Prime B550'],
            ['id'=>27,'id_group'=>30,'name'=>'Материнская плата MSI B450 Tomahawk'],
            ['id'=>28,'id_group'=>30,'name'=>'Материнская плата Gigabyte Z690'],
            ['id'=>29,'id_group'=>30,'name'=>'Материнская плата ASRock B660'],
            ['id'=>30,'id_group'=>30,'name'=>'Материнская плата ASUS ROG Strix B550'],
            ['id'=>31,'id_group'=>31,'name'=>'Процессор Intel Core i5-12400F'],
            ['id'=>32,'id_group'=>31,'name'=>'Процессор Intel Core i7-12700K'],
            ['id'=>33,'id_group'=>31,'name'=>'Процессор AMD Ryzen 5 5600X'],
            ['id'=>34,'id_group'=>31,'name'=>'Процессор AMD Ryzen 7 5800X'],
            ['id'=>35,'id_group'=>31,'name'=>'Процессор Intel Core i9-12900K'],
            ['id'=>36,'id_group'=>14,'name'=>'Моноблок Apple iMac 24'],
            ['id'=>37,'id_group'=>14,'name'=>'Моноблок Lenovo IdeaCentre AIO'],
            ['id'=>38,'id_group'=>14,'name'=>'Моноблок HP Pavilion 24'],
            ['id'=>39,'id_group'=>14,'name'=>'Моноблок ASUS Zen AiO'],
            ['id'=>40,'id_group'=>14,'name'=>'Моноблок Acer Aspire C24'],
            ['id'=>41,'id_group'=>15,'name'=>'Системный блок Gaming RTX 3060'],
            ['id'=>42,'id_group'=>15,'name'=>'Системный блок Gaming RTX 3070'],
            ['id'=>43,'id_group'=>15,'name'=>'Системный блок Office PC i5'],
            ['id'=>44,'id_group'=>15,'name'=>'Системный блок Office PC Ryzen 5'],
            ['id'=>45,'id_group'=>15,'name'=>'Системный блок Gaming RTX 3080'],
            ['id'=>46,'id_group'=>19,'name'=>'Холодильник LG DoorCooling'],
            ['id'=>47,'id_group'=>19,'name'=>'Холодильник Samsung No Frost'],
            ['id'=>48,'id_group'=>19,'name'=>'Холодильник Bosch Serie 4'],
            ['id'=>49,'id_group'=>19,'name'=>'Холодильник Indesit Total No Frost'],
            ['id'=>50,'id_group'=>19,'name'=>'Холодильник Beko двухкамерный'],
            ['id'=>51,'id_group'=>20,'name'=>'Морозильная камера ATLANT'],
            ['id'=>52,'id_group'=>20,'name'=>'Морозильная камера Liebherr'],
            ['id'=>53,'id_group'=>20,'name'=>'Морозильная камера Beko'],
            ['id'=>54,'id_group'=>20,'name'=>'Морозильная камера Indesit'],
            ['id'=>55,'id_group'=>20,'name'=>'Морозильная камера Haier'],
            ['id'=>56,'id_group'=>21,'name'=>'Стиральная машина LG Steam'],
            ['id'=>57,'id_group'=>21,'name'=>'Стиральная машина Samsung EcoBubble'],
            ['id'=>58,'id_group'=>21,'name'=>'Стиральная машина Bosch Serie 6'],
            ['id'=>59,'id_group'=>21,'name'=>'Стиральная машина Indesit'],
            ['id'=>60,'id_group'=>21,'name'=>'Стиральная машина Beko'],
            ['id'=>61,'id_group'=>22,'name'=>'Сушильная машина Bosch'],
            ['id'=>62,'id_group'=>22,'name'=>'Сушильная машина LG'],
            ['id'=>63,'id_group'=>22,'name'=>'Сушильная машина Samsung'],
            ['id'=>64,'id_group'=>22,'name'=>'Сушильная машина Beko'],
            ['id'=>65,'id_group'=>22,'name'=>'Сушильная машина Electrolux'],
            ['id'=>66,'id_group'=>23,'name'=>'Посудомоечная машина Bosch'],
            ['id'=>67,'id_group'=>23,'name'=>'Посудомоечная машина Siemens'],
            ['id'=>68,'id_group'=>23,'name'=>'Посудомоечная машина Beko'],
            ['id'=>69,'id_group'=>23,'name'=>'Посудомоечная машина Electrolux'],
            ['id'=>70,'id_group'=>23,'name'=>'Посудомоечная машина Weissgauff'],
            ['id'=>71,'id_group'=>32,'name'=>'Женская блуза классическая'],
            ['id'=>72,'id_group'=>32,'name'=>'Женская блуза офисная'],
            ['id'=>73,'id_group'=>32,'name'=>'Женская блуза шелковая'],
            ['id'=>74,'id_group'=>32,'name'=>'Женская блуза летняя'],
            ['id'=>75,'id_group'=>32,'name'=>'Женская блуза белая'],
            ['id'=>76,'id_group'=>33,'name'=>'Женская рубашка хлопковая'],
            ['id'=>77,'id_group'=>33,'name'=>'Женская рубашка oversize'],
            ['id'=>78,'id_group'=>33,'name'=>'Женская рубашка джинсовая'],
            ['id'=>79,'id_group'=>33,'name'=>'Женская рубашка офисная'],
            ['id'=>80,'id_group'=>33,'name'=>'Женская рубашка классическая'],
            ['id'=>81,'id_group'=>17,'name'=>'Мужские брюки классические'],
            ['id'=>82,'id_group'=>18,'name'=>'Мужская куртка зимняя'],

        ]);

        DB::table('prices')->insert([
            ['id'=>101,'id_product'=>1,'price'=>52490], 
            ['id'=>102,'id_product'=>2,'price'=>5755], 
            ['id'=>103,'id_product'=>3,'price'=>16480], 
            ['id'=>104,'id_product'=>4,'price'=>96990], 
            ['id'=>105,'id_product'=>5,'price'=>1896], 
            ['id'=>106,'id_product'=>6,'price'=>1843], 
            ['id'=>107,'id_product'=>7,'price'=>2356], 
            ['id'=>108,'id_product'=>8,'price'=>259], 
            ['id'=>109,'id_product'=>9,'price'=>308], 
            ['id'=>110,'id_product'=>10,'price'=>3108],
            ['id'=>111,'id_product'=>11,'price'=>12990],
            ['id'=>112,'id_product'=>12,'price'=>5490],
            ['id'=>113,'id_product'=>13,'price'=>3990],
            ['id'=>114,'id_product'=>14,'price'=>8990],
            ['id'=>115,'id_product'=>15,'price'=>18990],
            ['id'=>116,'id_product'=>16,'price'=>35990],
            ['id'=>117,'id_product'=>17,'price'=>47990],
            ['id'=>118,'id_product'=>18,'price'=>69990],
            ['id'=>119,'id_product'=>19,'price'=>28990],
            ['id'=>120,'id_product'=>20,'price'=>32990],
            ['id'=>121,'id_product'=>21,'price'=>4990],
            ['id'=>122,'id_product'=>22,'price'=>5990],
            ['id'=>123,'id_product'=>23,'price'=>11990],
            ['id'=>124,'id_product'=>24,'price'=>2590],
            ['id'=>125,'id_product'=>25,'price'=>6490],
            ['id'=>126,'id_product'=>26,'price'=>11990],
            ['id'=>127,'id_product'=>27,'price'=>8990],
            ['id'=>128,'id_product'=>28,'price'=>16990],
            ['id'=>129,'id_product'=>29,'price'=>10990],
            ['id'=>130,'id_product'=>30,'price'=>15990],
            ['id'=>131,'id_product'=>31,'price'=>19990],
            ['id'=>132,'id_product'=>32,'price'=>32990],
            ['id'=>133,'id_product'=>33,'price'=>18990],
            ['id'=>134,'id_product'=>34,'price'=>24990],
            ['id'=>135,'id_product'=>35,'price'=>58990],
            ['id'=>136,'id_product'=>36,'price'=>149990],
            ['id'=>137,'id_product'=>37,'price'=>69990],
            ['id'=>138,'id_product'=>38,'price'=>79990],
            ['id'=>139,'id_product'=>39,'price'=>89990],
            ['id'=>140,'id_product'=>40,'price'=>64990],
            ['id'=>141,'id_product'=>41,'price'=>85990],
            ['id'=>142,'id_product'=>42,'price'=>109990],
            ['id'=>143,'id_product'=>43,'price'=>45990],
            ['id'=>144,'id_product'=>44,'price'=>42990],
            ['id'=>145,'id_product'=>45,'price'=>139990],
            ['id'=>146,'id_product'=>46,'price'=>69990],
            ['id'=>147,'id_product'=>47,'price'=>74990],
            ['id'=>148,'id_product'=>48,'price'=>81990],
            ['id'=>149,'id_product'=>49,'price'=>55990],
            ['id'=>150,'id_product'=>50,'price'=>49990],
            ['id'=>151,'id_product'=>51,'price'=>34990],
            ['id'=>152,'id_product'=>52,'price'=>57990],
            ['id'=>153,'id_product'=>53,'price'=>28990],
            ['id'=>154,'id_product'=>54,'price'=>25990],
            ['id'=>155,'id_product'=>55,'price'=>31990],
            ['id'=>156,'id_product'=>56,'price'=>42990],
            ['id'=>157,'id_product'=>57,'price'=>39990],
            ['id'=>158,'id_product'=>58,'price'=>54990],
            ['id'=>159,'id_product'=>59,'price'=>25990],
            ['id'=>160,'id_product'=>60,'price'=>27990],
            ['id'=>161,'id_product'=>61,'price'=>49990],
            ['id'=>162,'id_product'=>62,'price'=>45990],
            ['id'=>163,'id_product'=>63,'price'=>47990],
            ['id'=>164,'id_product'=>64,'price'=>39990],
            ['id'=>165,'id_product'=>65,'price'=>52990],
            ['id'=>166,'id_product'=>66,'price'=>45990],
            ['id'=>167,'id_product'=>67,'price'=>51990],
            ['id'=>168,'id_product'=>68,'price'=>38990],
            ['id'=>169,'id_product'=>69,'price'=>42990],
            ['id'=>170,'id_product'=>70,'price'=>34990],
            ['id'=>171,'id_product'=>71,'price'=>1990],
            ['id'=>172,'id_product'=>72,'price'=>2290],
            ['id'=>173,'id_product'=>73,'price'=>3490],
            ['id'=>174,'id_product'=>74,'price'=>1790],
            ['id'=>175,'id_product'=>75,'price'=>2090],
            ['id'=>176,'id_product'=>76,'price'=>2590],
            ['id'=>177,'id_product'=>77,'price'=>2990],
            ['id'=>178,'id_product'=>78,'price'=>3190],
            ['id'=>179,'id_product'=>79,'price'=>2790],
            ['id'=>180,'id_product'=>80,'price'=>2390],
            ['id'=>181,'id_product'=>81,'price'=>3990],
            ['id'=>182,'id_product'=>82,'price'=>6990],
        ]);
    }
}